apiVersion: v1
kind: ConfigMap
metadata:
  name: smarthome-backend-config
  namespace: smarthome
data:
  HPPT_PORT: "3000"
  REDIS_SERVER: "redis://smarthome-redis-service.smarthome.svc.cluster.local:6380"
  TYPEORM_TYPE: "mysql"
  TYPEORM_HOST: "smarthome-mysql-service.smarthome.svc.cluster.local"
  TYPEORM_PORT: "43306"
  TYPEORM_USERNAME: "root"
  TYPEORM_PASSWORD: "P@ssw0rd"
  TYPEORM_DATABASE: "SMARTHOME"
  TOKEN_EXPIRE: "1d"
  JWT_SECRET: SMARTHOME
  SALT_ROUNDS: "9"
