apiVersion: apps/v1
kind: Deployment
metadata: 
  name: smarthome-backend
  namespace: smarthome
spec:
  selector:
    matchLabels:
      app: smarthome-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: smarthome-backend
    spec:
      containers:
      - name: smarthome-backend
        image: wachayathorn/smarthome:1.0.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
            protocol: TCP
        envFrom:
          - configMapRef:
              name: smarthome-backend-config
      imagePullSecrets:
      - name: docker-secret