apiVersion: v1
kind: PersistentVolume
metadata:
  name: smarthome-mysql-pv-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: smarthome-mysql-pv-volume-local
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/smarthome-mysql-data"