apiVersion: v1
kind: Service
metadata:
  name: smarthome-mysql-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: smarthome-mysql
  ports:
    - port: 43306
      targetPort: 3306
      protocol: TCP