apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarthome-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smarthome-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smarthome-mysql
    spec:
      containers:
        - image: mariadb:10.6.0
          name: smarthome-mysql
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: P@ssw0rd
            - name: MARIADB_DATABASE
              value: SMARTHOME
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: smarthome-mysql-pv-volume-claim
