apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarthome-mysql
  namespace: default
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: smarthome-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smarthome-mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: P@ssw0rd@Superuser
          ports:
            - containerPort: 3306
              protocol: TCP
              name: smarthome-mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: smarthome-mysql-pv-volume-claim