apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smarthome-redis-pv-volume-claim
  namespace: smarthome
spec:
  storageClassName: smarthome-redis-pv-volume-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi