apiVersion: v1
kind: Service
metadata:
  name: smarthome-redis-service
  namespace: smarthome
spec:
  type: NodePort
  selector:
    app: smarthome-redis
  ports:
    - port: 6380
      targetPort: 6379
      protocol: TCP